sonar.projectKey=Sample-Pad-Pro-Backend
sonar.projectName=Sample Pad Pro Backend

# Conexión local a SonarQube
sonar.host.url=http://localhost:9000
sonar.token=${env.SONAR_TOKEN}

# Configuración de rutas (NestJS)
sonar.sources=src
sonar.tests=test

# Exclusiones de archivos para evitar falsos positivos
sonar.exclusions=**/*.spec.ts,dist/**,node_modules/**

# Encoding
sonar.sourceEncoding=UTF-8

# Coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
